[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
absolute_monarchy = "D2VDfq9f7UaeuJVqpR5Qq1W4vBfqHbJWYSbvbE1Bsryc"
ark_program = "7Yp7HDMVapqkUQ9nPZRBaPbzn48DUbgZdw8EXyaeCiHX"
ark_protocol = "8BpSfZNw6f5yCxUvavqRNnpjuh7gPEZL7iRVXodctWwA"
conviction = "DnN713Fw9TFRiNfXL3uTNGyXUdktQr9VQsHnVRWLtc8p"
flat = "9y6z2L9hCjt9p6SuTw1q6vMfz4ZjwvMReMyLquYJNnRp"
military = "6A9RQDic1z5DfneBEyu4N7aPXmGC4wGQVAEzUUdYybDY"
polycentric = "9M7mVM8xbsM3K1f3VqTCwgmoANXtRzvKAEJCCDV32Fdu"
reclaim = "DovMZfoRztSgQ1SKx1M3UKwZz5fZtNbshX3qYSZHacZ4"
reclaim_protocol = "AR8NdxYxzCncZPppCeuJh7Rspd6L6WGFYhPNTm9WF2U1"
sociocracy = "HhSbFSfVpJj2LKHDs2W7wEfZcacN38UbauQFt1oKfCTQ"
sortition = "BTE5KLhjYqg6dhmUakXMNJkgYcsNiia5sQyp6wb1neqL"
standard = "2eTVXGSKCaTaivadMawTEz3h14FLwhyGTY64UBYLyZ6p"
the_ark_program = "9rkxTYZH7uF5kd3xt9yrbvMEUFbeJCkfwFzSeqhmkN76"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
